"""empty message

Revision ID: 122f093ab4c7
Revises: 7fd64e32e46b
Create Date: 2023-11-09 09:07:10.006744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122f093ab4c7'
down_revision = '7fd64e32e46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_autenticado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_autenticado')
    # ### end Alembic commands ###
