"""empty message

Revision ID: 4d78a3add7f6
Revises: 8e4617d96df6
Create Date: 2023-11-09 13:34:06.620269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d78a3add7f6'
down_revision = '8e4617d96df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_autenticado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username_logado', sa.String(length=255), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_autenticado', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('username_logado')

    # ### end Alembic commands ###
