"""empty message

Revision ID: 9f6d56a17f15
Revises: 4d78a3add7f6
Create Date: 2023-11-14 15:15:23.421929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6d56a17f15'
down_revision = '4d78a3add7f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assumido_por', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fechado_por', sa.String(length=255), nullable=True))
        batch_op.alter_column('sequencia_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('problema',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('nivel',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('nivel',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('problema',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('sequencia_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('fechado_por')
        batch_op.drop_column('assumido_por')

    # ### end Alembic commands ###
