"""empty message

Revision ID: bfc577094c45
Revises: 
Create Date: 2023-11-08 14:44:07.525564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc577094c45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('permissao', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chamados',
    sa.Column('sequencia_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('nivel', sa.String(length=100), nullable=False),
    sa.Column('data_create', sa.DateTime(), nullable=True),
    sa.Column('data_closed', sa.String(length=100), nullable=True),
    sa.Column('aberto_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aberto_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('sequencia_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chamados')
    op.drop_table('usuario')
    # ### end Alembic commands ###
